{{- if and .Values.config.secret.enabled (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nbomber-studio.fullname" . }}-config
  labels:
    {{- include "nbomber-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  config-override.json: |
    {{- toJson .Values.config.secret.data | nindent 4 }}
{{- end }}
