{{- if and .Values.trustedCAs.enabled .Values.trustedCAs.certs (not .Values.trustedCAs.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nbomber-studio.fullname" . }}-trusted-ca
  labels:
    {{- include "nbomber-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.trustedCAs.certs | nindent 2 }}
{{- end }}
